{{ if .Values.global.deploy_webhook_component }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Release.Namespace }}
  {{- if .Values.service.annotations }}
  annotations: 
  {{- range $k, $v := .Values.service.annotations }}
    {{$k}}: {{$v | quote }}
  {{- end }}
  {{- end}}
  {{- $baseLabels := dict "app" .Values.global.appName "releaseName" .Release.Name "version" .Values.deployment.version }}
  {{- $mergedLabels :=  merge $baseLabels .Values.service.labels }}
  labels:
    {{- range $k, $v := $mergedLabels }}
    {{ $k }}: {{ $v | quote }}
    {{- end}}
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    {{- $baseSelector := dict "app" .Values.global.appName "releaseName" .Release.Name "version" .Values.deployment.version }}
    {{- $mergedSelector :=  merge $baseSelector .Values.deployment.podLabels }}
    {{- range $k, $v := $mergedSelector }}
    {{ $k }}: {{ $v | quote }}
    {{- end}}
  type: {{ .Values.service.type }}
{{ end }}
