# name sould be the same as slug for simplicity
topics:
  - name: topic-1
    description: just some descroption for topics 1
  - name: topic-2
    description: just some descroption for topics 2
  - name: topic-3
    description: just some descroption for topics 3

tags:
  - name: tag-1
    description: just some descroption for tag 1
  - name: tag-2
    description: just some descroption for tag 2
  - name: tag-3
    description: just some descroption for tag 3
