# name sould be single words, prevent speces
topics:
  - name: Topic1
    description: just some descroption for topics 1
  - name: Topic2 
    description: just some descroption for topics 2
  - name: Topic3
    description: jjust some descroption for topics 3
  - name: Topic4
    description: just some descroption for topics 3

tags:
  - name: Tag1
    description: just some descroption for tag 1
  - name: Tag2
    description: just some descroption for tag 2
  - name: Tag3
    description: jjust some descroption for tag 3
  - name: Tag4
    description: just some descroption for tag 3
